name: env_tpp
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python==3.6.10
  - cudatoolkit==10.0.130-0
  - pytorch==1.2.0
  - torchvision==0.4.0
  - numpy==1.16.4
  - matplotlib==3.1.0
  - pip==19.2.2
  - tqdm==4.32.1
  - git==2.23.0
  - pytest==5.2.1
  - scipy==1.3.1
  - toolz==0.10.0
  - seaborn==0.9
  - scikit-learn==0.22.2.post1
  - pip:
#    - tick==0.6.0.0
# https://github.com/X-DataInitiative/tick/releases
#    - https://github.com/X-DataInitiative/tick/releases/download/v0.6/tick-0.6.0.0-cp36-cp36m-manylinux2010_x86_64.whl
#    - https://github.com/X-DataInitiative/tick/releases/download/v0.6/tick-0.6.0.0-cp37-cp37m-manylinux2010_x86_64.whl
    - requests==2.22.0
    - dill==0.3.1.1
    - Pillow==6.1
# May need to update conda gcc
# conda install -c anaconda gcc_linux-64
    - "--editable=git+https://github.com/aliutkus/torchsearchsorted.git@5e70e9f7491ab39b386963264e84492ab4c099c1#egg=torchsearchsorted"
    - imageio==2.6.1
    - mlflow==1.6.0
    - pandas==1.0.1
